apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: zipkin-observability-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - zipkin.istio-system.jhipster.35.241.183.73.nip.io
    - port:
        number: 80
        name: http2
        protocol: HTTP2
      hosts:
        - zipkin.istio-system.jhipster.35.241.183.73.nip.io
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: zipkin-gw-virtualservice
  namespace: istio-system
spec:
  hosts:
    - zipkin.istio-system.jhipster.35.241.183.73.nip.io
  gateways:
    - zipkin-observability-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: zipkin
